server:
    port: 8081

spring:
    application:
        name: Welcome-Api
boot:
    admin:
    client:
        url: http://localhost:1111/
eureka:
    client:
        service-url:
            default-zone: http://localhost:8761/eureka/
management:
    endpoints:
        web:
            exposure:
                include: '*'